# Generated by Django 5.1.6 on 2025-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0002_association_profilepic_user_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='profilePic',
            field=models.ImageField(blank=True, default='images/logo1', null=True, upload_to='associatePic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPic',
            field=models.ImageField(blank=True, default='images/propic.jpeg', null=True, upload_to='images'),
        ),
    ]
