# Generated by Django 5.1.6 on 2025-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0003_alter_association_profilepic_alter_user_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmember',
            name='adminAccept',
            field=models.BooleanField(default=False),
        ),
    ]
