# Generated by Django 5.1.6 on 2025-03-09 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0006_alter_servicerequest_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='amsApp.service'),
        ),
    ]
