# Generated by Django 5.1.6 on 2025-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0008_userfeedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacks',
            name='association',
            field=models.ManyToManyField(blank=True, related_name='feedbackAssociation', to='amsApp.association'),
        ),
    ]
